"""refactoring2

Revision ID: 2d18ec5c2573
Revises: 32781bfc53d3
Create Date: 2024-11-10 08:36:19.925260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d18ec5c2573'
down_revision: Union[str, None] = '32781bfc53d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logs_instance_id_fkey', 'logs', type_='foreignkey')
    op.drop_column('logs', 'instance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('instance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('logs_instance_id_fkey', 'logs', 'instances', ['instance_id'], ['id'])
    # ### end Alembic commands ###
