"""refactoring

Revision ID: 32781bfc53d3
Revises: 6754efdc72e7
Create Date: 2024-11-10 08:23:53.974940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32781bfc53d3'
down_revision: Union[str, None] = '6754efdc72e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ...
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('logs_instance_id_fkey', 'logs', type_='foreignkey')
    # op.create_foreign_key(None, 'logs', 'logs', ['instance_id'], ['instance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key('logs_instance_id_fkey', 'logs', 'instances', ['instance_id'], ['id'])
    # ### end Alembic commands ###
