"""init

Revision ID: 51eb71d2e48f
Revises: 
Create Date: 2024-11-09 13:57:49.889919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51eb71d2e48f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kind_id'), 'kind', ['id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('sw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kind'], ['kind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sw_id'), 'sw', ['id'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacture_number', sa.Integer(), nullable=True),
    sa.Column('schedule_interval', sa.Integer(), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('sw_version', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pwd_salt', sa.String(), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=True),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('sw', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kind'], ['kind.id'], ),
    sa.ForeignKeyConstraint(['sw'], ['sw.id'], ),
    sa.ForeignKeyConstraint(['task'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instances_id'), 'instances', ['id'], unique=False)
    op.create_index(op.f('ix_instances_manufacture_number'), 'instances', ['manufacture_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instances_manufacture_number'), table_name='instances')
    op.drop_index(op.f('ix_instances_id'), table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_sw_id'), table_name='sw')
    op.drop_table('sw')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_kind_id'), table_name='kind')
    op.drop_table('kind')
    # ### end Alembic commands ###
