"""refactoring

Revision ID: 6754efdc72e7
Revises: e8ad3c22cd22
Create Date: 2024-11-10 07:45:45.469404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6754efdc72e7'
down_revision: Union[str, None] = 'e8ad3c22cd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'logs', ['path'])
    op.drop_column('logs', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'logs', type_='unique')
    op.drop_column('logs', 'path')
    # ### end Alembic commands ###
