"""refactoring4

Revision ID: 86344f64140a
Revises: 19fc2958b207
Create Date: 2024-11-10 08:52:51.587442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86344f64140a'
down_revision: Union[str, None] = '19fc2958b207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('instance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logs', 'instances', ['instance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_column('logs', 'instance_id')
    # ### end Alembic commands ###
