version: "3.7"

services:
  back:
    image: 'fastapi'
    depends_on:
      - pgsql
    build:
      context: .
      dockerfile: fastapi.dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    environment:
      POSTGRES_HOST: 'pgsql'
      DATABASE_URL: ${DATABASE_URL}
  pgsql:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/var/lib/postgresql/data
  front:
    image: node:16-alpine
    container_name: react_front
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  pgsql:
  back:

# networks:
#   default:
#     external:
#       name: elastic_net